/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Database.Dados;
import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


/**
 *
 * @author Adriano
 */
public class FrmPrincipal extends javax.swing.JFrame {

    private static int option; // 1 - paciente   2 - medico  3 - consulta
    private static String selecionado; // armazena nome do item selecionado na jlist

    DefaultListModel modelo = new DefaultListModel();

    public FrmPrincipal() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.lblData.setText(this.getData());
        this.setSize(300, 410);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCadConsulta = new javax.swing.JButton();
        btnCadMedico = new javax.swing.JButton();
        btnCadPaciente = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnSair = new javax.swing.JButton();
        lblData = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnListPaciente = new javax.swing.JButton();
        btnListConsulta = new javax.swing.JButton();
        btnListMedico = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_lista = new javax.swing.JList();
        btnDeletar = new javax.swing.JButton();
        btnExibir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SCH - Menu Principal");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Cadastrar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        btnCadConsulta.setText("Consulta");
        btnCadConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadConsultaMouseClicked(evt);
            }
        });

        btnCadMedico.setText("Médico");
        btnCadMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadMedicoMouseClicked(evt);
            }
        });

        btnCadPaciente.setText("Paciente");
        btnCadPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadPacienteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCadConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(btnCadMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45)
                .addComponent(btnCadPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCadConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        btnSair.setText("Sair");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });

        lblData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblData.setText("00/00/0000");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/DATA.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblData)
                            .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Listar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        btnListPaciente.setText("Paciente");
        btnListPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListPacienteMouseClicked(evt);
            }
        });

        btnListConsulta.setText("Consulta");
        btnListConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListConsultaMouseClicked(evt);
            }
        });

        btnListMedico.setText("Médico");
        btnListMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListMedicoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnListConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(btnListMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnListPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnListConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jl_lista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jl_lista.setVisibleRowCount(5);
        jScrollPane1.setViewportView(jl_lista);

        btnDeletar.setBackground(new java.awt.Color(255, 0, 0));
        btnDeletar.setForeground(new java.awt.Color(255, 255, 255));
        btnDeletar.setText("Deletar");
        btnDeletar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnDeletar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeletarMouseClicked(evt);
            }
        });

        btnExibir.setText("Exibir");
        btnExibir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExibirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btnExibir, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExibir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static int getSelecionado() {
        return Integer.parseInt(selecionado);
    }

    public static int getOption() {
        return option;
    }

//pega a data Atual do Sistema
    public String getData() {
        String dataFormatada;
        SimpleDateFormat formatarData = new SimpleDateFormat("dd/MM/yyyy");
        Date data = new Date(System.currentTimeMillis());
        dataFormatada = formatarData.format(data);

        return dataFormatada;
    }

    private void btnCadPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadPacienteMouseClicked
        FrmCadPaciente cadPaciente = new FrmCadPaciente();
        cadPaciente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadPacienteMouseClicked

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_btnSairMouseClicked

    private void btnListPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListPacienteMouseClicked
        FrmPrincipal.option = 1;
        if (carregarList(option)) {
            modelo.clear();
            this.setSize(555, 410);
            for (int i = 0; i <= Dados.getPaciente().size() - 1; i++) {
                modelo.addElement(Dados.getPaciente().get(i).getNome());
            }
            jl_lista.setModel(modelo);
        }
    }//GEN-LAST:event_btnListPacienteMouseClicked

    private void btnListMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListMedicoMouseClicked
        FrmPrincipal.option = 2;
        if (carregarList(option)) {
            modelo.clear();
            this.setSize(555, 410);
            for (int i = 0; i <= Dados.getMedico().size() - 1; i++) {
                modelo.addElement(Dados.getMedico().get(i).getNome());
            }
            jl_lista.setModel(modelo);
        }
    }//GEN-LAST:event_btnListMedicoMouseClicked

    private void btnCadMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadMedicoMouseClicked
        FrmCadMedico cadMedico = new FrmCadMedico();
        cadMedico.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadMedicoMouseClicked

    private void btnCadConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadConsultaMouseClicked
        if (autorizaConsulta()) {
            FrmCadConsulta cadConsulta = new FrmCadConsulta();
            cadConsulta.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnCadConsultaMouseClicked

    private void btnListConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListConsultaMouseClicked
        FrmPrincipal.option = 3;
        if (carregarList(option)) {
            modelo.clear();
            this.setSize(555, 410);
            for (int i = 0; i <= Dados.getConsulta().size() - 1; i++) {
                modelo.addElement(Dados.getConsulta().get(i).getNumeroConsulta());
            }
            jl_lista.setModel(modelo);
        }
    }//GEN-LAST:event_btnListConsultaMouseClicked

    private void btnDeletarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeletarMouseClicked
        selecionado = String.valueOf(jl_lista.getSelectedValue());
        removerObjetoList(option);
    }//GEN-LAST:event_btnDeletarMouseClicked

    private void btnExibirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExibirMouseClicked
        try {
            selecionado = String.valueOf(jl_lista.getSelectedIndex());
            FrmExibicao exibir = new FrmExibicao();
            exibir.setVisible(true);
            this.dispose();
        } catch (ArrayIndexOutOfBoundsException erro_lista_vazia) {
            JOptionPane.showMessageDialog(null, "Nenhum item selecionado!", "ERRO", 0);
        }
    }//GEN-LAST:event_btnExibirMouseClicked

    private boolean autorizaConsulta() {
        // lança janela de erro caso não tenha ao menos um médico e um pacientes cadastrados
        if (Dados.getMedico().size() <= 0) {
            JOptionPane.showMessageDialog(null, "Nenhum médico cadastrado para consultas!", "ERRO", 0);
            return false;
        } else if (Dados.getPaciente().size() <= 0) {
            JOptionPane.showMessageDialog(null, "Nenhum paciente cadastrado para consultas!", "ERRO", 0);
            return false;
            // caso não lance os erros, autoriza o preenchimento do formulário de cadastro de consultas
        }
        return true;
    }

    private void removerObjetoList(int option) {
        switch (option) {
            case 1:     // remover paciente
                Dados.delPaciente(selecionado);
                modelo.clear();
                if (!Dados.getPaciente().isEmpty()) {
                    for (int i = Dados.getPaciente().size() - 1; i >= 0; i--) {
                        modelo.addElement(Dados.getPaciente().get(i).getNome());
                        jl_lista.setModel(modelo);
                    }

                }
                this.setSize(300, 410);
                break;
            case 2:     // remover medico
                Dados.delMedico(selecionado);
                modelo.clear();
                if (!Dados.getMedico().isEmpty()) {
                    for (int i = Dados.getMedico().size() - 1; i >= 0; i--) {
                        modelo.addElement(Dados.getMedico().get(i).getNome());
                        jl_lista.setModel(modelo);
                    }

                }
                this.setSize(300, 410);
                break;
            case 3:     // remover consulta
                Dados.delConsulta(selecionado);
                modelo.clear();
                if (!Dados.getConsulta().isEmpty()) {
                    for (int i = Dados.getConsulta().size() - 1; i >= 0; i--) {
                        modelo.addElement(Dados.getConsulta().get(i).getNumeroConsulta());
                        jl_lista.setModel(modelo);
                    }
                    this.setSize(300, 410);
                    break;
                }
        }
    }

    private boolean carregarList(int opt) {
        switch (opt) {
            case 1:     // paciente
                // mensagem de erro ao exibir lista vazia
                if (Dados.getPaciente().size() <= 0) {
                    JOptionPane.showMessageDialog(null, "Nenhum paciente cadastrado!", "ERRO", 0);
                    this.setSize(300, 410);
                    return false;
                }
                // autoriza exibição da lista
                return true;
            case 2:     // medico
                // mensagem de erro ao exibir lista vazia
                if (Dados.getMedico().size() <= 0) {
                    JOptionPane.showMessageDialog(null, "Nenhum médico cadastrado!", "ERRO", 0);
                    this.setSize(300, 410);
                    return false;
                }
                // autoriza exibição da lista
                return true;
            case 3:     // consulta
                // mensagem de erro ao exibir lista vazia
                if (Dados.getConsulta().size() <= 0) {
                    JOptionPane.showMessageDialog(null, "Nenhuma consulta cadastrada!", "ERRO", 0);
                    this.setSize(300, 410);
                    return false;
                }
                // autoriza exibição da lista
                return true;
        }
        // em caso de algum erro excepcional
        return false;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadConsulta;
    private javax.swing.JButton btnCadMedico;
    private javax.swing.JButton btnCadPaciente;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnExibir;
    private javax.swing.JButton btnListConsulta;
    private javax.swing.JButton btnListMedico;
    private javax.swing.JButton btnListPaciente;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList jl_lista;
    private javax.swing.JLabel lblData;
    // End of variables declaration//GEN-END:variables
}
